[lint]
select = ["ALL"]
ignore = [
    "CPY001",
    "D100",
    "D101",
    "D104",
    "I001",
    "I002",
    "INP001",
    "N802",
    "N818",
    "PLR0917",
    "TRY300",
    "TRY301",
]

[lint.per-file-ignores]
"app/**" = [
    "ARG002",
    "BLE001",
    "TC001",
    "TC002",
]
"app/console/commands/**" = [
    "RUF012",
]
"app/http/schemas/constraints/**" = [
    "PLR2004",
]
"app/models/**" = [
    "FBT003",
    "RUF012",
]
"config/**" = [
    "E501",
]
"database/**" = [
    "E501",
    "S608",
    "TC001",
]
"routes/**" = [
    "E501",
    "S608",
]

[lint.pydocstyle]
convention = "numpy"
